### ISSUE TITLE
Brightness getting dim&brighten

### ISSUE THREAD

**Issue by Pg-Pi3Gey** [bitrvmpd/sailfish-santoni#1]
Brightness Getting a little dim and brighten even after setting brightness as manual. Happening even at a stable light surrounding and at dark too

attaching logs as per requested.
[journalctl.log](https://github.com/bitrvmpd/sailfish-santoni/files/1882771/journalctl.log)
[logcat.log](https://github.com/bitrvmpd/sailfish-santoni/files/1882772/logcat.log)
[dmesga.log](https://github.com/bitrvmpd/sailfish-santoni/files/1882773/dmesga.log)

**Comment by bitrvmpd** [comment]
Please attach files here directly.

**Comment by bitrvmpd** [comment]
I need more people reporting this, because I can't find anything weird on those logs.

**Comment by Pg-Pi3Gey** [comment]
Try to set Brightness to auto and not manual. Then try checking it

**Comment by bitrvmpd** [comment]
Ok, in manual mode it never happens, only in Auto.
I found a spot in my house were this happens. I would not called it a bug, it's just too sensitive, I will look if there's a way to reduce it.

**Comment by Pg-Pi3Gey** [comment]
Will Give the latest beta a try.. and see if it's somewhat Improved or not
