### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by 0v3rcr1t** [bitrvmpd/sailfish-santoni#2]
VPN connects, but no system traffic goes through VPN
PS: OpenVPN

**Comment by bitrvmpd** [comment]
No logs attached? No vpn config?. A google search lead me to this:

https://together.jolla.com/question/169838/bug-openvpn-default-route-directive-from-server-ignored/

**Comment by bitrvmpd** [comment]
Also, try this:

https://together.jolla.com/question/167526/open-vpn-astrill-intex-aquafish/?answer=167826#post-id-167826

**Comment by bitrvmpd** [comment]
I'll close this. If you still have issues with VPN, please report here if you've tried the proposed solutions.
