### ISSUE TITLE
About android support

### ISSUE THREAD

**Issue by nkrapivin** [bitrvmpd/sailfish-santoni#4]
Quote from Jolla website:

> 1 Installing Android applications on your Sailfish device Installing Android applications is done via application stores and via .apk files. Before installing any Android apps one must install AndroidTM Support which is available in the Jolla Store.

Tried to search Yandex (which is the best choice for me)
Nothing, why?

**Comment by nkrapivin** [comment]
Oh, I found aliendalvik ports to nexus 5 and nexus 4. They're just using modified envsetup script (this script points to android libraries)

**Comment by nkrapivin** [comment]
Welp, it does NOT work.
Last question.
Can I use your "base LOS" I mean lineage-14.1-20180401-UNOFFICIAL-santoni.zip as normal ROM?
Then I will install SFOS as second system via DualBootPatcher.
So I will get lineage-14.1-20180401-UNOFFICIAL-santoni.zip installed as primary and lineage-14.1-20180401-UNOFFICIAL-santoni.zip + SFOS installed secondary.
Will it work? That is the question.

**Comment by bitrvmpd** [comment]
Don't try to run alien-dalvik again please, that's piracy. Only anbox/sfdroid are the legal way to run android apps on sailfishOS (it's still a WIP tho).

> Can I use your "base LOS" I mean lineage-14.1-20180401-UNOFFICIAL-santoni.zip as normal ROM?
Then I will install SFOS as second system via DualBootPatcher.
So I will get lineage-14.1-20180401-UNOFFICIAL-santoni.zip installed as primary and lineage-14.1-20180401-UNOFFICIAL-santoni.zip + SFOS installed secondary.
Will it work? That is the question.

It's a build from April 1st (April fools'). You will have a message saying "you may be a victim of software counterfeiting" (that's the "joke"). [More info](https://www.reddit.com/r/LineageOS/comments/88ppge/changelog_17_building_blockchains_genuine/dwp5ql8/) 

Dualbooting is not my goal, neither is of this project. You could try and report it here. I will close this issue. Why? simple:
> THIS IS NOT ANDROID. it's SailfishOS a Community Port, what does it mean? = No APK Support.

**Comment by nkrapivin** [comment]
Thanks! But DualBootPatcher at now broken, "updating ramdisk" will brick ramdisk. I will try MultiROM. And yeah LOSCoin is the best cryptocurrency!

**Comment by nkrapivin** [comment]
It didn't worked. Fails to install (unknown command [[]). But mbtool refuses to patch kernel if installation "failed"

**Comment by bitrvmpd** [comment]
Hmm after I tried a couple of things, it seems that the culprit is the update-binary. So i can't do much for now. Thanks anyway!

**Comment by nkrapivin** [comment]
mbtool is not patching kernel because it's "anti-mess" protection.

If installation of zip ERROR-ed just unmount chroot and end the installation.
And yes 1st April build by itself works, but after flashing SFOS it just bootloops.
I think this is a fstab problem
(and if we switch to primary firmware via DualBootUtilities zip file it boots so primary firmware works)
DON'T TRY LATEST APRIL BUILDS! THEY ARE BROKEN! AFTER UPDATING RAMDISK DEVICE BOOTLOOPS. (any device, even my attempt to port dbp to galaxy tab e fails, but after checkouting march commit it works)

Try this build https://dbp.noobdev.io/files/9.3.0.r473.gd901dad5/Android/DualBootPatcherAndroid-9.3.0.r473.gd901dad5-snapshot.apk or this https://dbp.noobdev.io/files/9.3.0.r469.g7b51d591/Android/DualBootPatcherAndroid-9.3.0.r469.g7b51d591-snapshot.apk these are two March builds.

**Comment by nkrapivin** [comment]
Sorry for my bad English.

**Comment by bitrvmpd** [comment]
Tomorrow I'll test something to get rid of the error message :)
