### ISSUE TITLE
update

### ISSUE THREAD

**Issue by spiritEcosse** [bitrvmpd/sailfish-santoni#6]
please tell me, can I somehow update, without a cycle - remove everything, put it again? PS: Thank you for your work.

**Comment by bitrvmpd** [comment]
I don't understand, are you asking me if you can update w/o wiping everything ?

You could try flashing the new SFOS update over the old one and post in this issue your results, but until I don't enable OTAs the recommended way is doing the complete process (factory reset, install LOS, install sailfishOS).

**Comment by bitrvmpd** [comment]
Also, i will close this issue. You didn't follow the template.
