### ISSUE TITLE
I got error 7 when I install sailfish rom in my TWRP

### ISSUE THREAD

**Issue by bintangmesir** [bitrvmpd/sailfish-santoni#8]
LineageOS build:
  > 

SailfishOS build:
  > 

#### Steps to reproduce

---

**Comment by bitrvmpd** [comment]
1. You didn't filled the form as expected.
2. Use the official TWRP and follow the instructions https://github.com/bitrvmpd/sailfish-santoni/blob/master/README.md#how-to-install-updated-download-links-are-here

**Comment by bitrvmpd** [comment]
It was caused by the way the newer TWRP handle errors.
Solution: Downgrade to TWRP 3.2.2-0
1851f94fa8aa883184eb86a4227f13e92f77904c

Sorry for the -long- delay (but you didn't provide any additional info)
